FROM prefecthq/prefect:2.6.5-python3.8

COPY . /app/
WORKDIR /app

# Hacky way to pull in the .env file
RUN export $(cat development.env)

# For CloudRun purposes
EXPOSE 8080

RUN pip install -r requirements.txt

CMD [ "bash", "deploy/entrypoint.sh" ]