name: 'nba_analytics'
version: '1.0.0'
config-version: 2

profile: 'nba_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  nba_analytics:
    base:
      +materialized: view
    staging:
      +materialized: table
    summary:
      +materialized: table
      +schema: __clean

vars:
  db_name: nba-player-analytics