name: 'nba_analytics'
version: '1.0.0'
config-version: 2

profile: 'nba_analytics'
model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  nba_analytics:
    base:
      +materialized: view
      +schema: _base
    
    staging:
      +materialized: table
      +schema: _staging
    
    clean:
      +materialized: table
      +schema: _clean
    
    player_summaries:
      +materialized: view
      +schema: _clean

vars:
  db_name: nba-player-analytics