nba_analytics:
  target: db
  outputs:
    db:
      type: bigquery
      method: service-account
      keyfile: ../service_accounts/gcp_load_creds.json
      project: nba-player-analytics
      dataset: nba_dbt
      threads: 4
      location: us